[workspace]
[package]
name = "ncn_listener"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.18.1"
solana-sdk = "1.18.1"
solana-transaction-status = "1.18.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
chrono = "0.4.40"
